<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-OHIPPB3J" failures="0" tests="6" name="com.edu.test.Skulist1" time="0.643" errors="1" timestamp="28 12æœˆ 2018 00:56:18 GMT" skipped="5">
  <testcase classname="com.edu.test.Skulist1" name="setUp" time="0.643">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at java.base/java.lang.Class.forName0(Native Method)
at java.base/java.lang.Class.forName(Class.java:292)
at com.edu.utils.DbHelper.init(DbHelper.java:51)
at com.edu.utils.DbHelper.getInstance(DbHelper.java:40)
at com.edu.core.BaseTest.setUp(BaseTest.java:13)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:520)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- setUp -->
  <testcase classname="com.edu.test.Skulist1" name="TestSkuListById2" time="0.000">
    <skipped/>
  </testcase> <!-- TestSkuListById2 -->
  <testcase classname="com.edu.test.Skulist1" name="TestSkuListById3" time="0.000">
    <skipped/>
  </testcase> <!-- TestSkuListById3 -->
  <testcase classname="com.edu.test.Skulist1" name="TestSkuListById1" time="0.000">
    <skipped/>
  </testcase> <!-- TestSkuListById1 -->
  <testcase classname="com.edu.test.Skulist1" name="Skulist1" time="0.000">
    <skipped/>
  </testcase> <!-- Skulist1 -->
  <testcase classname="com.edu.test.Skulist1" name="TestSkuListByWrongIdType" time="0.000">
    <skipped/>
  </testcase> <!-- TestSkuListByWrongIdType -->
</testsuite> <!-- com.edu.test.Skulist1 -->
