<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="LAPTOP-OHIPPB3J" failures="1" tests="6" name="test" time="1.566" errors="0" timestamp="21 12月 2018 08:49:35 GMT">
  <testcase classname="com.edu.scene.test.Login_Test" name="login_test" time="0.608"/>
  <testcase classname="com.edu.scene.test.SkuList_Test" name="skulist_test" time="0.114"/>
  <testcase classname="com.edu.scene.test.AddressList_Test" name="getAddressList_test" time="0.182">
    <failure type="java.lang.AssertionError" message="expected [success] but found [请重新登录]">
      <![CDATA[java.lang.AssertionError: expected [success] but found [请重新登录]
at com.edu.scene.test.AddressList_Test.getAddressList_test(AddressList_Test.java:34)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.base/java.lang.Thread.run(Thread.java:844)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- getAddressList_test -->
  <testcase classname="com.edu.scene.test.GetTranspotFee_Test" name="getFee_test" time="0.113"/>
  <testcase classname="com.edu.scene.test.AddAddress_Test" name="addAddress_test" time="0.263"/>
  <testcase classname="com.edu.scene.test.AddressDelete_Test" name="addressDelete_test" time="0.225"/>
  <testcase classname="com.edu.scene.test.Login_Test" name="testlogin" time="0.0">
    <ignored/>
  </testcase> <!-- testlogin -->
</testsuite> <!-- test -->
