<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="PC" failures="6" tests="9" name="查询运费" time="1.265" errors="0" timestamp="26 12月 2018 10:32:41 GMT">
  <testcase classname="com.edu.test.TransFeeTest" name="feeTest" time="0.539"/>
  <testcase classname="com.edu.test.TransFeeTest" name="feeTest2" time="0.08"/>
  <testcase classname="com.edu.test.TransFeeTest" name="feeTest3" time="0.08">
    <failure type="java.lang.AssertionError" message="expected [请求失败] but found [success]">
      <![CDATA[java.lang.AssertionError: expected [请求失败] but found [success]
at com.edu.test.TransFeeTest.feeTest3(Unknown Source)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.base/java.lang.Thread.run(Thread.java:844)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- feeTest3 -->
  <testcase classname="com.edu.test.TransFeeTest" name="feeTest4" time="0.095"/>
  <testcase classname="com.edu.test.TransFeeTest" name="feeTest5" time="0.09">
    <failure type="java.lang.AssertionError" message="expected [请求失败] but found [success]">
      <![CDATA[java.lang.AssertionError: expected [请求失败] but found [success]
at com.edu.test.TransFeeTest.feeTest5(Unknown Source)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.base/java.lang.Thread.run(Thread.java:844)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- feeTest5 -->
  <testcase classname="com.edu.test.TransFeeTest" name="feeTest6" time="0.09">
    <failure type="java.lang.AssertionError" message="expected [请求失败] but found [success]">
      <![CDATA[java.lang.AssertionError: expected [请求失败] but found [success]
at com.edu.test.TransFeeTest.feeTest6(Unknown Source)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.base/java.lang.Thread.run(Thread.java:844)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- feeTest6 -->
  <testcase classname="com.edu.test.TransFeeTest" name="feeTest7" time="0.09">
    <failure type="java.lang.AssertionError" message="expected [请求失败] but found [success]">
      <![CDATA[java.lang.AssertionError: expected [请求失败] but found [success]
at com.edu.test.TransFeeTest.feeTest7(Unknown Source)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.base/java.lang.Thread.run(Thread.java:844)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- feeTest7 -->
  <testcase classname="com.edu.test.TransFeeTest" name="feeTest8" time="0.1">
    <failure type="java.lang.AssertionError" message="expected [请求失败] but found [success]">
      <![CDATA[java.lang.AssertionError: expected [请求失败] but found [success]
at com.edu.test.TransFeeTest.feeTest8(Unknown Source)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.base/java.lang.Thread.run(Thread.java:844)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- feeTest8 -->
  <testcase classname="com.edu.test.TransFeeTest" name="feeTest9" time="0.08">
    <failure type="java.lang.AssertionError" message="expected [请求失败] but found [success]">
      <![CDATA[java.lang.AssertionError: expected [请求失败] but found [success]
at com.edu.test.TransFeeTest.feeTest9(Unknown Source)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.base/java.lang.Thread.run(Thread.java:844)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- feeTest9 -->
  <testcase classname="com.edu.test.TransFeeTest" name="feeTest10" time="0.0">
    <ignored/>
  </testcase> <!-- feeTest10 -->
</testsuite> <!-- 查询运费 -->
