<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="接口场景测试"
           tests="6"
           failures="2"
           errors="0"
           skipped="0"
           time="4.375">
  <properties />
            <testcase name="skulist_test6" time="0.350" classname="com.edu.scene.test.QingGuoScene1_Test">
                <failure type="java.lang.AssertionError"
                  message="expected [400] but found [200]"
              >
<![CDATA[java.lang.AssertionError: expected [400] but found [200]
  org.testng.Assert.fail(Assert.java:96)
  org.testng.Assert.failNotEquals(Assert.java:776)
  org.testng.Assert.assertEqualsImpl(Assert.java:137)
  org.testng.Assert.assertEquals(Assert.java:118)
  org.testng.Assert.assertEquals(Assert.java:652)
  org.testng.Assert.assertEquals(Assert.java:662)
  com.edu.scene.test.QingGuoScene1_Test.skulist_test6(QingGuoScene1_Test.java:69)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.base/java.lang.reflect.Method.invoke(Method.java:564)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:648)
  org.testng.TestRunner.run(TestRunner.java:505)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
  org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
  org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
  org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
  java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
  java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
  java.base/java.lang.Thread.run(Thread.java:844)
]]>
      </failure>

          </testcase>
            <testcase name="skulist_test5" time="1.184" classname="com.edu.scene.test.QingGuoScene1_Test">
                <failure type="java.lang.AssertionError"
                  message="expected [400] but found [200]"
              >
<![CDATA[java.lang.AssertionError: expected [400] but found [200]
  org.testng.Assert.fail(Assert.java:96)
  org.testng.Assert.failNotEquals(Assert.java:776)
  org.testng.Assert.assertEqualsImpl(Assert.java:137)
  org.testng.Assert.assertEquals(Assert.java:118)
  org.testng.Assert.assertEquals(Assert.java:652)
  org.testng.Assert.assertEquals(Assert.java:662)
  com.edu.scene.test.QingGuoScene1_Test.skulist_test5(QingGuoScene1_Test.java:60)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.base/java.lang.reflect.Method.invoke(Method.java:564)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:648)
  org.testng.TestRunner.run(TestRunner.java:505)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
  org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
  org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
  org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
  java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
  java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
  java.base/java.lang.Thread.run(Thread.java:844)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="skulist_test4" time="1.526" classname="com.edu.scene.test.QingGuoScene1_Test" />
                <testcase name="skulist_test1" time="0.718" classname="com.edu.scene.test.QingGuoScene1_Test" />
                <testcase name="skulist_test2" time="0.219" classname="com.edu.scene.test.QingGuoScene1_Test" />
                <testcase name="skulist_test3" time="0.378" classname="com.edu.scene.test.QingGuoScene1_Test" />
      
</testsuite>
